src/me/coley/recaf/Recaf.java

Hi, I saw your project and thought it looked interesting. I noticed you hardcoded the Look & Feel, so I added the ability to set the it using the environment variable COL_RECAF_LAF. Note that as far as I know this only seems to work when the app is launched from the command line.

Add ability to set Look & Feel via environment variable.

---

pom.xml
src/me/coley/recaf/ui/component/list/OpcodeCellRenderer.java
src/me/coley/recaf/ui/component/list/RenderFormatter.java

1) pom.xml fix, to include en.json in the default build (i.e. "git clone, mvn package")
2) Error handling robustness for when getType() fails

fix pom.xml resource path

---

src/me/coley/recaf/ui/FxWindow.java

 Fix editor open mechanism

---

pom.xml
src/me/coley/recaf/Input.java
src/me/coley/recaf/ui/FxWindow.java

Expand file tree recursively

---

src/me/coley/recaf/ui/FormatFactory.java

```java
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@TestAnnotation(values1 = {"v1", "v2"}, values2 = {Exception.class, Error.class}, values4 = @Retention(RetentionPolicy.CLASS))
@TestAnnotation2(@TestAnnotation(values2 = {}, values3 = {@Target(ElementType.TYPE)}))
public @interface TestAnnotation {
String[] values1() default {};
Class<?>[] values2();
Target[] values3() default {};
Retention values4() default @Retention(RetentionPolicy.SOURCE);
}
@Target({ElementType.TYPE, ElementType.ANNOTATION_TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface TestAnnotation2 {
TestAnnotation value();
}
```

Complete support for all allowed annotation value types

---

src/me/coley/recaf/config/impl/ConfKeybinds.java
src/me/coley/recaf/ui/component/editor/InsnListEditor.java
src/resources/lang/en.json
src/resources/lang/zh-cn.json

* Add method instructions search

add instructions search function

---

src/me/coley/recaf/bytecode/Asm.java
src/me/coley/recaf/config/impl/ConfKeybinds.java
src/me/coley/recaf/ui/component/editor/InsnListEditor.java
src/resources/lang/en.json
src/resources/lang/zh-cn.json

Node(s) duplicate added
Node(s) shift up added
Node(s) shift down added
* Summary of additions
* Summary of bugs fixed

Instructions Editor shortcuts 

---

pom.xml
src/main/java/me/coley/recaf/Input.java
src/main/java/me/coley/recaf/bytecode/ClassUtil.java
src/main/java/me/coley/recaf/bytecode/analysis/ClassVertex.java
src/main/java/me/coley/recaf/parse/assembly/util/AutoComplete.java
src/main/java/me/coley/recaf/parse/source/RegionMapper.java
src/main/java/me/coley/recaf/util/CFRPipeline.java
src/main/java/me/coley/recaf/util/Classpath.java
src/main/java/me/coley/recaf/util/Define.java
src/main/java/me/coley/recaf/util/Dependencies.java
src/main/java/me/coley/recaf/workspace/ClassesMap.java
src/main/java/me/coley/recaf/workspace/InputBuilder.java
src/test/java/me/coley/recaf/AutoCompleteTest.java

* Rewrite some code
* Rewrite some more code related to the code mentioned above.
* Add support for arrays when completing descriptor (e.g `[Ljava/lang/String;`)
* Add unit tests for auto-completion (incomplete)
* Add [JUnit Jupiter Params](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests) component to test dependencies
* Add [Hamcrest](https://hamcrest.org/JavaHamcrest/) to test dependencies
* Partially fix auto-completion doesn't suggest any of the bootstrap classes - see #134.

 Refactor auto-completion, classpath util & related code

---

src/main/java/me/coley/recaf/Input.java

Fix .class files are exported in a wrong way

---

src/main/java/me/coley/recaf/ui/controls/WorkspaceNavigator.java

Fixes NPE that is thrown when Recaf starts without `--workspace` option

Fix NPE when launching Recaf  without workspace

---

src/main/java/me/coley/recaf/parse/assembly/impl/MultiANewArray.java

Fix MultiANewArray TYPE field incorrect parsing

---

src/main/java/me/coley/recaf/Recaf.java
src/main/java/me/coley/recaf/config/Config.java
src/main/java/me/coley/recaf/config/ConfigManager.java
src/main/java/me/coley/recaf/control/gui/GuiController.java
src/main/java/me/coley/recaf/ui/MainWindow.java

Start JavaFX thread properly
Recaf storage directory can be accessed with
`me.coley.recaf.Recaf.getStorageDirectory()`
Solves #177

Cleanup code, prperly start JavaFX thread

---

checkstyle.xml
pom.xml
src/main/java/java/lang/module/ModuleFinder.java
src/main/java/java/lang/module/ModuleReader.java
src/main/java/java/lang/module/ModuleReference.java
src/main/java/me/coley/recaf/util/ClasspathUtil.java

Cleaner way to scan for bootstrap classes

---

src/main/java/me/coley/recaf/ui/controls/text/TextPane.java
src/main/java/me/coley/recaf/util/UnicodeUtil.java
src/test/java/me/coley/recaf/UnicodeTest.java

Display unicode characters correctly

---

src/main/java/me/coley/recaf/Recaf.java
src/main/java/me/coley/recaf/util/self/SelfPatcher.java

Expected behaivor for `recaf.home` property, fix for #197

Enhancements

---

pom.xml
src/main/java/me/coley/recaf/Recaf.java
src/main/java/me/coley/recaf/ui/controls/text/EditorPane.java
src/main/java/me/coley/recaf/ui/controls/view/ClassViewport.java

Keep scroll position after reloaded.

---

src/main/java/me/coley/recaf/util/self/SelfDependencyPatcher.java

Download JVM dependent jfx binaries

---

src/main/java/me/coley/recaf/util/LangUtil.java

Also don't leave file handles open.

fix: Properly load multiple lang files from classpath.

---

src/main/java/me/coley/recaf/ui/MainMenu.java
src/main/resources/translations/en.json
src/main/resources/translations/zh-cn.json

feat: File -> Close all

---

src/main/java/me/coley/recaf/parse/bytecode/MethodAssembler.java
src/main/java/me/coley/recaf/parse/bytecode/MethodCompilation.java
src/main/java/me/coley/recaf/parse/bytecode/ast/AliasAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/Compilable.java
src/main/java/me/coley/recaf/parse/bytecode/ast/FieldInsnAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/IincInsnAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/InsnAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/Instruction.java
src/main/java/me/coley/recaf/parse/bytecode/ast/IntInsnAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/InvokeDynamicAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/JumpInsnAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/LabelAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/LdcInsnAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/LineInsnAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/LookupSwitchInsnAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/MethodInsnAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/MultiArrayInsnAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/TableSwitchInsnAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/TypeInsnAST.java
src/main/java/me/coley/recaf/parse/bytecode/ast/VarInsnAST.java
src/main/java/me/coley/recaf/ui/controls/text/BytecodeLocalHelper.java

Extended API for AST parsing. Required for #245

feat: Extend API for AST.

---

src/main/java/me/coley/recaf/control/headless/JLineEditor.java
src/main/java/me/coley/recaf/mapping/Mappings.java
src/main/java/me/coley/recaf/plugin/api/ClassVisitorPlugin.java
src/main/java/me/coley/recaf/ui/controls/node/ClassNodeEditorPane.java
src/main/java/me/coley/recaf/ui/controls/text/BytecodeEditorPane.java
src/main/java/me/coley/recaf/workspace/WorkspaceClassWriter.java

Plugins now can intercept ClassVisitors.
That allows us to probably implement #246 as a plugin instead.

feat: add class visitor plugin

---

pom.xml
src/main/java/me/coley/recaf/Agent.java
src/main/java/me/coley/recaf/Recaf.java
src/main/java/me/coley/recaf/config/ConfigManager.java
src/main/java/me/coley/recaf/control/Controller.java
src/main/java/me/coley/recaf/control/gui/GuiController.java
src/main/java/me/coley/recaf/plugin/PluginFolderSource.java
src/main/java/me/coley/recaf/plugin/api/ExitPlugin.java
src/main/java/me/coley/recaf/ui/MainWindow.java
src/main/java/me/coley/recaf/ui/controls/AttachPane.java
src/main/java/me/coley/recaf/ui/controls/UpdatePane.java
src/main/java/me/coley/recaf/util/ClassUtil.java
src/main/java/me/coley/recaf/util/RecafClassLoader.java
src/main/java/me/coley/recaf/util/ThreadUtil.java
src/main/java/me/coley/recaf/util/struct/VMUtil.java
src/main/java/me/coley/recaf/workspace/InstrumentationResource.java
src/main/resources/logback.xml

Outdated dependencies were causing Recaf to crash.

fix: start Recaf in isolated class loader

---

src/main/java/me/coley/recaf/plugin/api/AttachPlugin.java
src/main/java/me/coley/recaf/ui/controls/AttachPane.java

feat: Attach plugin

---

src/main/java/me/coley/recaf/parse/bytecode/ast/LineInsnAST.java

fix: line numbers assigned to correct values

---

src/main/java/me/coley/recaf/config/ConfKeybinding.java

* The 'meta' modifier key is now supported for keybindings

fix: Added support for 'meta' modifier key

---

src/main/java/me/coley/recaf/Recaf.java
src/main/java/me/coley/recaf/ui/controls/JvmCreationPane.java
src/main/java/me/coley/recaf/util/Log.java
src/main/java/me/coley/recaf/util/ProcessUtil.java
src/main/java/me/coley/recaf/util/VMUtil.java

refactor: More verbose information when creating new JVM.

---

src/main/java/me/coley/recaf/Recaf.java
src/main/java/me/coley/recaf/util/ClasspathUtil.java
src/main/java/me/coley/recaf/util/VMUtil.java
src/main/java/me/coley/recaf/util/self/SelfDependencyPatcher.java

fix: patch JDK reflection filters

---

src/main/java/me/coley/recaf/Recaf.java
src/main/java/me/coley/recaf/plugin/PluginFolderSource.java
src/main/java/me/coley/recaf/util/VMUtil.java

fix: use native methods to get class fields

---

src/main/java/me/coley/recaf/config/ConfDisplay.java
src/main/java/me/coley/recaf/ui/MainMenu.java
src/main/java/me/coley/recaf/ui/MainWindow.java
src/main/java/me/coley/recaf/ui/controls/ConfigPane.java
src/main/resources/translations/en.json

* Allow config to use system menubar
* Remove window icon
* Add dock icon

macOS experience improvements

---

build.gradle
recaf-core/build.gradle
recaf-core/src/main/java/me/coley/recaf/Controller.java
recaf-core/src/main/java/me/coley/recaf/Recaf.java
recaf-core/src/main/java/me/coley/recaf/RecafConstants.java
recaf-core/src/main/java/me/coley/recaf/Services.java
recaf-core/src/main/java/me/coley/recaf/decompile/DecompileOption.java
recaf-core/src/main/java/me/coley/recaf/decompile/DecompileResult.java
recaf-core/src/main/java/me/coley/recaf/decompile/Decompiler.java
recaf-core/src/main/java/me/coley/recaf/graph/InheritanceGraph.java
recaf-core/src/main/java/me/coley/recaf/graph/InheritanceVertex.java
recaf-core/src/main/java/me/coley/recaf/workspace/Workspace.java
recaf-core/src/main/java/me/coley/recaf/workspace/resource/ClassInfo.java
recaf-core/src/main/java/me/coley/recaf/workspace/resource/MemberInfo.java
recaf-core/src/main/java/me/coley/recaf/workspace/resource/Resources.java
recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/ClassContentSource.java
recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/ContainerContentSource.java
recaf-core/src/test/java/me/coley/recaf/graph/InheritanceGraphTests.java

Adding in a simple inheritance graph to 3X.
Still WIP while I contemplate a proper design approach for this.

Implement inheritance graph

---

recaf-core/src/main/java/me/coley/recaf/compile/CompileManager.java
recaf-core/src/main/java/me/coley/recaf/compile/CompileMap.java
recaf-core/src/main/java/me/coley/recaf/compile/CompileOption.java
recaf-core/src/main/java/me/coley/recaf/compile/Compiler.java
recaf-core/src/main/java/me/coley/recaf/compile/CompilerResult.java
recaf-core/src/main/java/me/coley/recaf/decompile/DecompileManager.java
recaf-core/src/main/java/me/coley/recaf/decompile/DecompileResult.java
recaf-core/src/main/java/me/coley/recaf/decompile/Decompiler.java
recaf-core/src/main/java/me/coley/recaf/plugin/tools/Tool.java
recaf-core/src/main/java/me/coley/recaf/plugin/tools/ToolManager.java
recaf-core/src/main/java/me/coley/recaf/plugin/tools/ToolOption.java
recaf-core/src/main/java/me/coley/recaf/plugin/tools/ToolResult.java
recaf-core/src/test/java/me/coley/recaf/graph/InheritanceGraphTests.java

Generally speaking, a tool is anything that takes in some inputs _(options and parameters)_ and emits a result/error.
For example:
* Compilers have flags, take in source, emit compiled code
* Decompilers have flags, take in compiled code, emit source
This PR lays out a base for tools and implements both the basic compiler/decompiler bases with it.

Tool abstractions and compiler layout

---

src/main/java/me/coley/recaf/config/ConfKeybinding.java

Support for mac key map.
* Summary of additions
Instead of using ctrl+key shortcuts, osx is using ⌘(Command)+key shortcuts.
In Recaf's code viewer,default key binding for copy and paste is  ⌘(Command)+C and ⌘(Command)+V , I need use both ⌘(Command)+key and Ctrl+Key to get work done without supporting mac's keymap .
NONE
* Summary of bugs fixed

Support for mac key map.

---

src/main/java/me/coley/recaf/decompile/cfr/CfrDecompiler.java

NONE
* Summary of additions
* Summary of bugs fixed
* #344

Fix #344 cfr inner class name replace

---

pom.xml
src/main/java/java/lang/Module.java
src/main/java/java/lang/ModuleLayer.java
src/main/java/java/lang/module/Module.java
src/main/java/java/lang/module/ModuleFinder.java
src/main/java/me/coley/recaf/Recaf.java
src/main/java/me/coley/recaf/util/Java9Util.java
src/main/java/me/coley/recaf/util/VMUtil.java
src/main/java/me/coley/recaf/workspace/InstrumentationResource.java

Replace permit library

---

src/main/java/me/coley/recaf/mapping/MappingImpl.java
src/main/java/me/coley/recaf/mapping/TSrgMappings.java
src/main/java/me/coley/recaf/ui/MainMenu.java
src/test/java/me/coley/recaf/RemappingTest.java
src/test/resources/inherit-method-map-tsrg.txt

- Added support for tsrg mappings.
- Added tsrg test

feat: tsrg mappings

---

src/main/java/me/coley/recaf/util/Java9Util.java
src/main/java/me/coley/recaf/util/VMUtil.java

Recaf does not work on JDK16+ due to new restrictions.

fix: bypass JEP396

---

src/main/java/me/coley/recaf/config/ConfKeybinding.java
src/main/java/me/coley/recaf/ui/controls/KeybindField.java

* Fixed bad swap view default bind
* Fixed close window keybind activating if you edit it and set it to itself
* Fixed keybind fields keeping focus after a keybind is set

General keybind fixes

---

src/main/java/me/coley/recaf/Recaf.java
src/main/java/me/coley/recaf/command/impl/Export.java
src/main/java/me/coley/recaf/command/impl/LoadWorkspace.java
src/main/java/me/coley/recaf/control/gui/GuiController.java
src/main/java/me/coley/recaf/ui/controls/tree/ClassFolderItem.java
src/main/java/me/coley/recaf/util/IOUtil.java
src/main/java/me/coley/recaf/workspace/EntryLoader.java
src/main/java/me/coley/recaf/workspace/JarResource.java
src/main/java/me/coley/recaf/workspace/WarResource.java

Detect an input based on file headers
Detect class files by it's header
Optimize directory pruning
Proper (?) dock name for MacOS users
Fixed #391 
Fixed an error when user attempts to load invalid input

Update file detection/saving

---

src/main/resources/style/ui-default.css

* Fixed drag popup CSS on UI default theme
Solves https://github.com/Col-E/Recaf/issues/412

Fixed drag popup CSS on UI default theme

---

build.gradle
recaf-core/src/main/java/me/coley/recaf/util/ByteHeaderUtil.java
recaf-ui/build.gradle
recaf-ui/src/main/java/me/coley/recaf/ui/FileView.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/elf/ElfExplorerPane.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/elf/ElfHeaderDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/elf/ProgramHeaderDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/elf/ProgramHeaderTableDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/elf/SectionHeaderDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/elf/SectionHeaderTableDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/elf/StringTableDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/elf/StringTableTableDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/elf/TableDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/pe/DosTableDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/pe/ExportDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/pe/ExportTableDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/pe/FileTableDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/pe/ImportDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/pe/ImportTableDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/pe/OptionalTableDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/pe/PEExplorerPane.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/pe/SectionTableDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/pe/TableDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/pe/TableSectionDisplayMode.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/table/SizedDataTypeTable.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/table/TableByte.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/table/TableDword.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/table/TableGeneric.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/table/TableQword.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/table/TableWord.java

* View headers of the ELF format, most importantly strings

ELF explorer

---

recaf-ui/src/main/java/me/coley/recaf/ui/pane/pe/PEExplorerPane.java

* Fix export directory option in PE explorer pane appearing when no export directory is available

Fix export directory option in PE explorer pane appearing when no export directory is available

---

src/main/java/me/coley/recaf/command/impl/Export.java
src/main/java/me/coley/recaf/util/VMUtil.java

Potentially https://github.com/Col-E/Recaf/issues/397

Allow export of multiple zip entries with the same name

---

src/main/java/me/coley/recaf/command/impl/LoadWorkspace.java
src/main/java/me/coley/recaf/compiler/JavacCompiler.java
src/main/java/me/coley/recaf/compiler/JavacTargetVersion.java
src/main/java/me/coley/recaf/compiler/ResourceVirtualJavaFileObject.java
src/main/java/me/coley/recaf/control/gui/GuiController.java
src/main/java/me/coley/recaf/ui/controls/text/JavaEditorPane.java
src/main/java/me/coley/recaf/workspace/Workspace.java

In-memory classpath for javac
Removed temp jar writing (no longer needed, resource consuming for large archives)

Add in-memory classpath for javac

---

recaf-ui/src/main/java/me/coley/recaf/config/ConfigRegistry.java
recaf-ui/src/main/java/me/coley/recaf/config/container/DisplayConfig.java
recaf-ui/src/main/java/me/coley/recaf/presentation/GuiPresentation.java
recaf-ui/src/main/java/me/coley/recaf/ui/control/config/ConfigLanguage.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/ConfigPane.java
recaf-ui/src/main/java/me/coley/recaf/ui/util/Lang.java
recaf-ui/src/main/resources/translations/de_DE.lang
recaf-ui/src/main/resources/translations/en.lang
recaf-ui/src/main/resources/translations/zh_CN.lang
recaf-utils/src/main/java/me/coley/recaf/util/InternalPath.java
recaf-utils/src/main/java/me/coley/recaf/util/SelfReferenceUtil.java

* Users can now select their language in the config tab

User language config

---

recaf-ui/src/main/resources/translations/cs_CZ.lang

* A cs_CZ translation for the dev3 branch
* No bugs fixed

Czech translation for 3.x

---

.github/workflows/build.yml
.github/workflows/display_test_results.yml

Nothing
Fix test results not being shown on prs from forks

Fix test results not being shown on prs from forks

---

recaf-core/src/main/java/me/coley/recaf/mapping/MappingsAdapter.java
recaf-core/src/main/java/me/coley/recaf/mapping/impl/SimpleMappings.java
recaf-core/src/main/java/me/coley/recaf/mapping/impl/TinyV1Mappings.java

Nothing added
* Mappings no longer throw errors when using simple mapping fields that are mapped
* Parses simple mapped field names correctly

Fixes mappings throwing error

---

recaf-core/src/main/java/me/coley/recaf/Services.java
recaf-core/src/main/java/me/coley/recaf/compile/CompilerManager.java
recaf-core/src/main/java/me/coley/recaf/decompile/DecompileManager.java
recaf-ui/src/main/java/me/coley/recaf/config/container/CompilerConfig.java
recaf-ui/src/main/java/me/coley/recaf/config/container/DecompilerConfig.java
recaf-ui/src/main/java/me/coley/recaf/ui/control/code/java/JavaArea.java
recaf-ui/src/main/java/me/coley/recaf/ui/control/config/ConfigCompiler.java
recaf-ui/src/main/java/me/coley/recaf/ui/control/config/ConfigDecompiler.java
recaf-ui/src/main/java/me/coley/recaf/ui/control/config/ConfigEnum.java
recaf-ui/src/main/java/me/coley/recaf/ui/control/config/ConfigPos.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/ConfigPane.java
recaf-ui/src/main/resources/translations/en_US.lang

* Add combo box for compiler& decompiler implementation
* Add combo box for enumerators
* Add waffle selector for JavaFX pos enum
* Add fallback decompiler to manager
* Add option to disable decompiler timeout
* Rename CompileManager to CompilerManager
There are now (as of writing this) no unsupported field types in the config window!

Config UI additions & disable decompiler timeout

---

recaf-ui/src/main/java/me/coley/recaf/ui/control/code/java/JavaArea.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/DecompilePane.java

* Push additional decompiler timeout code

Push additional decompiler timeout code

---

recaf-ui/src/main/java/me/coley/recaf/config/container/EditorConfig.java

* Add int bounds to hex columns slider

Add int bounds to hex columns slider

---

src/main/java/me/coley/recaf/config/ConfKeybinding.java
src/main/java/me/coley/recaf/ui/controls/FontSlider.java
src/main/java/me/coley/recaf/ui/controls/tree/JavaResourceCell.java
src/main/java/me/coley/recaf/ui/controls/view/ClassViewport.java
src/main/resources/style/base.css
src/main/resources/translations/en.json

* New keybinds to increase/decrease editor font size
* None

Add keybinds to change editor font size

---

recaf-ui/src/main/resources/translations/zh_CN.lang

Fixed badly formatted translation key-pair.

Fix chinese translations

---

build.gradle
recaf-launcher/build.gradle

https://docs.gradle.org/current/userguide/toolchains.html

Use Gradle Java Toolchains instead of having requirement on Java version required to run gradle.

---

src/main/java/me/coley/recaf/plugin/PluginFolderSource.java

* The translation file of plugins will now be loaded
* none

Load plugin translation files

---

build.gradle
recaf-core/build.gradle
recaf-core/src/main/java/me/coley/recaf/ssvm/RemoteBootClassLoader.java
recaf-core/src/main/java/me/coley/recaf/ssvm/VirtualMachineUtil.java
recaf-core/src/main/java/me/coley/recaf/ssvm/asm/RecafOpcodes.java
recaf-core/src/main/java/me/coley/recaf/ssvm/debugger/BreakpointInstructionProcessor.java
recaf-core/src/main/java/me/coley/recaf/ssvm/debugger/BreakpointObserver.java
recaf-core/src/main/java/me/coley/recaf/ssvm/debugger/Debugger.java
recaf-core/src/main/java/me/coley/recaf/ssvm/debugger/DebuggerBreakpointNode.java
recaf-core/src/main/java/me/coley/recaf/ssvm/instrumentation/ClassFileTransformer.java
recaf-core/src/main/java/me/coley/recaf/ssvm/instrumentation/InstrumentingBootClassLoader.java
recaf-core/src/main/java/me/coley/recaf/ssvm/instrumentation/InstrumentingClassDefiner.java
recaf-jdk/README.md
recaf-jdk/build.gradle
recaf-jdk/src/main/java/dev/xdark/recaf/jdk/JavaUtil.java
recaf-jdk/src/main/java/dev/xdark/recaf/jdk/launch/ProcessLaunchOptions.java
recaf-jdk/src/main/java/dev/xdark/recaf/jdk/properties/JdkProperties.java
recaf-jdk/src/main/java/dev/xdark/recaf/jdk/properties/JdkPropertiesDump.java
recaf-jdk/src/main/java/dev/xdark/recaf/jdk/resources/JdkPropertiesDump.java
recaf-jdk/src/main/java/dev/xdark/recaf/jdk/resources/JdkResources.java
recaf-jdk/src/main/java/dev/xdark/recaf/jdk/resources/JdkResourcesServer.java
recaf-jdk/src/main/java/dev/xdark/recaf/jdk/resources/ToolConstant.java
settings.gradle

Begin ssvm integration
#154 time has come

Runtime simulation

---

src/main/java/me/coley/recaf/util/EscapeUtil.java

Fix double backslash before escaped unicode character causing lexing error
* Fixes https://github.com/Col-E/Recaf/issues/513

Fix double backslash before escaped unicode character causing lexing error

---

src/main/java/me/coley/recaf/ui/MainMenu.java

* Add Jadx mapping file support

Add Jadx mapping file to mapping file dialog

---

recaf-ui/src/main/java/me/coley/recaf/ui/control/ManifestArea.java
recaf-ui/src/main/java/me/coley/recaf/ui/control/TextView.java
recaf-ui/src/main/java/me/coley/recaf/ui/control/code/Languages.java

Added support for Hyperlinking to main class in manfiest (as for #288)
Nothing fixed

Added support Hyperlinking to main class in manifest. (#288)

---

recaf-ui/src/main/java/me/coley/recaf/ui/context/ClassContextBuilder.java
recaf-ui/src/main/java/me/coley/recaf/ui/context/FileContextBuilder.java
recaf-ui/src/main/resources/translations/en_US.lang

* Added a warning for when trying to rename a file or a class to a name that is already present in the resource (#478)
* No bugs fixed

Added warning for renaming classes and files (#478)

---

recaf-ui/src/main/resources/translations/de_DE.lang

Just a quick german translation push

Updated german language translations

---

recaf-assembler/build.gradle
recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/BaseElement.java
recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/Element.java
recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/arch/AbstractDefinition.java
recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/arch/FieldDefinition.java
recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/arch/MethodDefinition.java
recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/meta/Signature.java
recaf-assembler/src/main/java/me/coley/recaf/assemble/pipeline/AssemblerPipeline.java
recaf-assembler/src/main/java/me/coley/recaf/assemble/transformer/JasmToAstTransformer.java
recaf-ui/src/main/java/me/coley/recaf/config/container/AssemblerConfig.java
recaf-ui/src/main/java/me/coley/recaf/ui/control/code/bytecode/AssemblerArea.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/assembler/AssemblerPane.java
recaf-ui/src/main/resources/translations/en_US.lang

- Added context menus for instructions
- Bugs 🎲 🤔 
- Annotations not showing up on field
- Signature not showing up at all
- Lables not wrapped

Assembler context menus for instruction

---

recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/arch/MethodDefinition.java
recaf-assembler/src/main/java/me/coley/recaf/assemble/transformer/JasmToAstTransformer.java
recaf-assembler/src/test/java/me/coley/recaf/assemble/InstructionParseTests.java

Fix name escaping in Assembler

---

PRIMER.md

Fixed typo in PRIMER.md

---

build.gradle
recaf-core/build.gradle
recaf-core/src/main/java/me/coley/recaf/decompile/DecompileManager.java
recaf-core/src/main/java/me/coley/recaf/decompile/procyon/ProcyonDecompiler.java
recaf-core/src/main/java/me/coley/recaf/decompile/procyon/ResourceTypeLoader.java
recaf-core/src/main/java/me/coley/recaf/decompile/procyon/WorkspaceTypeLoader.java

Add procyon decompiler

---

recaf-ui/src/main/resources/translations/cs_CZ.lang

* updated Czech translation with better grammar
* translated missing keys

fix: update czech translation

---

recaf-ui/src/main/java/me/coley/recaf/config/ConfigRegistry.java
recaf-ui/src/main/java/me/coley/recaf/config/container/DisplayConfig.java
recaf-ui/src/main/java/me/coley/recaf/config/container/KeybindConfig.java
recaf-ui/src/main/java/me/coley/recaf/ui/ClassView.java
recaf-ui/src/main/java/me/coley/recaf/ui/FileView.java
recaf-ui/src/main/java/me/coley/recaf/ui/behavior/FontSizeChangeable.java
recaf-ui/src/main/java/me/coley/recaf/ui/control/TextView.java
recaf-ui/src/main/java/me/coley/recaf/ui/control/code/SyntaxArea.java
recaf-ui/src/main/java/me/coley/recaf/ui/control/config/ConfigRanged.java
recaf-ui/src/main/java/me/coley/recaf/ui/docking/RecafDockingManager.java
recaf-ui/src/main/java/me/coley/recaf/ui/docking/impl/ClassTab.java
recaf-ui/src/main/java/me/coley/recaf/ui/docking/impl/FileTab.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/BinaryXmlPane.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/DecompilePane.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/DiffViewPane.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/SmaliAssemblerPane.java
recaf-ui/src/main/resources/translations/en_US.lang

- Add scrolling with control key and also with a shortcut changing font size
TODO:

Changing font size

---

recaf-core/src/main/java/me/coley/recaf/code/FileInfo.java
recaf-core/src/main/java/me/coley/recaf/search/query/TextQuery.java
recaf-ui/src/main/java/me/coley/recaf/ui/FileView.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/DiffViewPane.java
recaf-ui/src/main/java/me/coley/recaf/ui/util/CellFactory.java
recaf-ui/src/main/java/me/coley/recaf/ui/util/Icons.java

- https://github.com/Col-E/recaf-3x-issues/issues/106
Co-authored by: @xxDark

Blinking no more in workspace outline for files and classes

---

recaf-core/src/main/java/me/coley/recaf/code/ClassInfo.java
recaf-core/src/main/java/me/coley/recaf/code/CommonClassInfo.java
recaf-core/src/main/java/me/coley/recaf/code/DexClassInfo.java
recaf-core/src/main/java/me/coley/recaf/code/InnerClassInfo.java
recaf-core/src/main/java/me/coley/recaf/code/MemberInfo.java
recaf-core/src/main/java/me/coley/recaf/code/OuterMethod.java
recaf-core/src/main/java/me/coley/recaf/code/OuterMethodInfo.java
recaf-ui/src/main/java/me/coley/recaf/ui/control/tree/OutlineTree.java
recaf-ui/src/main/java/me/coley/recaf/ui/pane/outline/OutlinePane.java
recaf-utils/src/main/java/me/coley/recaf/util/Streams.java

* Outer method in breadcrumbs
* Anonymous and method local classes in class outline
* https://github.com/Col-E/recaf-3x-issues/issues/110

Fix local classes and add outer method in breadcrumbs

---

recaf-ui/src/main/java/me/coley/recaf/util/JFXInjection.java

Addressing https://github.com/Col-E/recaf-3x-issues/issues/114

Providing more information about dependency downloads

---

recaf-ui/src/main/java/me/coley/recaf/ui/control/PannableImageView.java

- Fixed small zoom bug that sometimes occurs

Fix zoom in PannableImageView

---

recaf-assembler/src/main/java/me/coley/recaf/assemble/transformer/JasmToAstTransformer.java

- Fixed NaNf not being a constant

Fixed `NaNf` not being a constant

---

recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/insn/LdcInstruction.java

* Fix ow2 handle cast towards HandleInfo

Fix ow2 handle cast towards HandleInfo

---

recaf-ui/src/main/resources/translations/de_DE.lang

The en_US file has gained a lot of new keys since the last German translation, this PR adds translations for said new keys.
Several keys were improperly translated (e.g. informal capitalization, "sie" -> "Sie"), these have been fixed.

update german translations

---

recaf-ui/src/main/java/software/coley/recaf/services/config/factories/IntegerComponentFactory.java
recaf-ui/src/main/java/software/coley/recaf/services/config/factories/NumberComponentFactory.java
recaf-ui/src/main/java/software/coley/recaf/services/config/factories/StringComponentFactory.java
recaf-ui/src/main/java/software/coley/recaf/util/Effects.java
recaf-ui/src/main/resources/translations/sv_SE.lang

- Introduced a number input box for Config Options that uses type Integer.
- Implemented a String input box for Config Options that uses type String.
- Wrote a Swedish translation of Recafs dialogoues
- No more "Unsupporrted java.lang.Integer/java.lang.String

[Feature] Added New Input Boxes for Config Options and Wrote Swedish Translation

---

src/main/java/me/coley/recaf/Recaf.java

fix: infinite loading on launch

---

recaf-ui/src/main/java/software/coley/recaf/workspace/PathExportingManager.java

Exported class files are no longer exported as .class.class

[BUGFIX] Remove .class.class extension

---

recaf-core/src/main/java/software/coley/recaf/services/decompile/AbstractJvmDecompiler.java

Fix jvm bytecode filter removal not removing

---

README.md
recaf-ui/src/main/resources/translations/pl_PL.lang

[+](feat:) Added a Polish translation
[+](fix:) Fixed README.MD having the wrong path for jar output.

Added Polish translation and fixed README typo.

---

recaf-ui/src/main/java/software/coley/recaf/services/translation/LangConfig.java
recaf-ui/src/main/resources/translations/ja_JP.lang

* Added Japanese language file for selection.
(I am a native speaker of Japanese and English as my second language.)

feat: Add localisation: Japanese(ja_JP)
