Col-E/Recaf

.gitignore, pom.xml, src/me/coley/recaf/util/Streams.java
`Charset.defaultCharset()` will return different charsets on different platforms. For example, this method returns `GBK` in China, which will result in some unintelligible texts like this:
I hope my expression are understandable, I'm not native speakers.
=> Fix a encoding problem

src/me/coley/recaf/ui/component/ReflectiveFieldNodeItem.java
While modifying class member attributes I got a NPE since there is no current value  (in contrast to static fields). The NPE was silently dropped and the dialog won't open. 
Thus I just skipped the editor.setValue().
The swap in line 162 is not a bug but just a suggestion of my Intellij to avoid further NPE's if valueClass becomes NULL for some reason. (although I just see this must possibly be considered at line 169, too)
=> NPE for member fields

src/me/coley/recaf/config/impl/ConfDisplay.java, src/me/coley/recaf/util/Lang.java
So if the chosen translation is outdated, it can fallback gracefully to English instead of showing error messages.
=> Always load default language

src/main/java/me/coley/recaf/util/Classpath.java, src/main/java/me/coley/recaf/util/Dependencies.java
Returns scanning of boot classpath on JVM 9 and later versions, checking of version is done by checking `java.class.version` system property
=> Scan boot classpath on JVM 9 and later

src/main/java/me/coley/recaf/search/ClassReferenceQuery.java, src/main/java/me/coley/recaf/search/Context.java, src/main/java/me/coley/recaf/search/MemberReferenceQuery.java, src/main/java/me/coley/recaf/search/SearchCollector.java, src/main/java/me/coley/recaf/search/SearchResult.java
This is related to #164.
If there was [an `Lists.concat` method in Guava](//github.com/google/guava/pull/1029), we can avoid the copying in `getAllResults()` too, but I guess not...
=>  Remove the redundant copying in overlapping results calculation

src/main/java/me/coley/recaf/control/gui/GuiController.java, src/main/java/me/coley/recaf/ui/MainWindow.java, src/main/java/me/coley/recaf/ui/controls/ViewportTabs.java
Fixes a bug when a class with the same name cannot be opened again.
=> Fix viewports are not cleared after workspace load

src/main/java/me/coley/recaf/ui/MainMenu.java
* Additional check for null in ```me.coley.recaf.ui.MainMenu#addLibrary(...)```
* ```NullPointerException``` when add library with empty workspace (doesn't loaded jar file):
=> fix: NPE if the workspace not initialized

src/main/java/me/coley/recaf/Recaf.java, src/main/java/me/coley/recaf/plugin/PluginsManager.java, src/main/java/me/coley/recaf/plugin/api/InternalApi.java, src/main/java/me/coley/recaf/plugin/api/InternalPlugin.java, src/main/java/me/coley/recaf/ui/MainMenu.java, src/main/java/me/coley/recaf/ui/MainWindow.java, src/main/java/me/coley/recaf/ui/controls/HistoryPane.java, src/main/java/me/coley/recaf/ui/controls/PluginManagerPane.java, src/main/java/me/coley/recaf/ui/controls/tree/RootItem.java, src/main/java/me/coley/recaf/util/InternalElement.java, src/main/java/me/coley/recaf/util/struct/InternalBiConsumer.java, src/main/java/me/coley/recaf/util/struct/InternalConsumer.java, src/main/java/me/coley/recaf/util/struct/VMUtil.java, src/main/java/me/coley/recaf/workspace/JavaResource.java
Before that commit, Recaf kept additional set of workspace listeners for it's own purposes.
This PR remove that set, and adds internal plugins instead.
Everything that must not be used by plugin developers is marked as `@InternalApi`. However, that also allows users to load/unload plugins on-the-fly.
=> refactor: Remove API flaw

src/main/java/me/coley/recaf/config/ConfBackend.java, src/main/java/me/coley/recaf/mapping/AsmMappingUtils.java, src/main/java/me/coley/recaf/mapping/Mappings.java, src/main/java/me/coley/recaf/ui/MainMenu.java, src/main/java/me/coley/recaf/workspace/Workspace.java, src/main/resources/translations/en.json, src/test/java/me/coley/recaf/mapping/AsmMappingUtilsTest.java
First, thanks for creating this project! This could have helped me a lot with a project some years ago, so I took a look at partially implementing #281.
The workspace now keeps track of mappings applied to it in an aggregated map conforming to the internal ASM format. This aggregated map can then be used to provide a basic export facility for mappings in that format (the Simple format).
The mapping in the workspace only stores the end result of all applied mappings. That means that rename operations "a -> b -> c" are folded together and stored as "a -> c". To enable this, `AsmMappingUtils` contains code to apply new mapping rules to existing mappings by just operating on the mapping Strings itself rather than a real class graph.
While it would be nice to be able to export to all the …
=> feat: Track applied renames in workspace and enable mapping export

src/main/java/me/coley/recaf/mapping/EnigmaMappings.java
When Enigma sees a class without a packagename (which seems to be common for JavaME MIDlets, e.g. DoomRPG mentioned in #309), it puts it inside a dummy package 'none/'. Recaf does not do that, so Enigma mappings for those package-less classes don't work when imported into Recaf. I've been dealing with it by removing all instances of string ```none``` with ```sed```, but it would be nice to do this inside Recaf's parser.
=> Handle none/ package

recaf-core/src/main/java/me/coley/recaf/Controller.java, recaf-core/src/main/java/me/coley/recaf/Services.java, recaf-core/src/main/java/me/coley/recaf/decompile/DecompileManager.java, recaf-core/src/main/java/me/coley/recaf/decompile/DecompileOption.java, recaf-core/src/main/java/me/coley/recaf/decompile/DecompileResult.java, recaf-core/src/main/java/me/coley/recaf/decompile/Decompiler.java
* Outline for decompiler implementations
* Decompile manager that will allow 3rd parties to register their own decompilers
The goal is to abstract away references to decompilers via `DecompileManager` so that plugins can add their own decompilers and it should just integrate seamlessly.
=> Base abstractions for managing decompiler impls

src/main/java/me/coley/recaf/compiler/JavacTargetVersion.java, src/main/java/me/coley/recaf/ui/controls/text/JavaEditorPane.java
* I noticed that comparation of class version and max supported target version was wrong, resulting in that version of the target class version would always become the highest version supported by javac. In my case the original class was v7 but when I edited it would be compiled as v8 which was not correct and caused an issue as the resulting jar was to be run by a version 1.7 jvm.
*  Small fix for default of max target version, the log message and the returned version were not consistent.
=> Javac target fix

src/main/java/me/coley/recaf/Recaf.java
Fixes #313.
Just returning seems to be the best option for me. picocli prints a nice help message anyway.
Another option would be to set `CommandLine#setUnmatchedArgumentsAllowed` to true, but this would make spotting typos harder.
=> fix: Unknown cli argument crashes application

recaf-core/build.gradle, recaf-core/src/main/java/me/coley/recaf/compile/CompilerDiagnostic.java, recaf-core/src/main/java/me/coley/recaf/compile/CompilerResult.java, recaf-core/src/main/java/me/coley/recaf/compile/javac/ForwardingListener.java, recaf-core/src/main/java/me/coley/recaf/compile/javac/JavacCompiler.java, recaf-core/src/main/java/me/coley/recaf/compile/javac/JavacListener.java, recaf-core/src/main/java/me/coley/recaf/compile/javac/VirtualFileManager.java, recaf-core/src/main/java/me/coley/recaf/compile/javac/VirtualJavaFileObject.java, recaf-core/src/main/java/me/coley/recaf/compile/javac/VirtualUnitMap.java, recaf-core/src/main/java/me/coley/recaf/plugin/tools/Tool.java, recaf-core/src/main/java/me/coley/recaf/util/Directories.java, recaf-core/src/main/java/me/coley/recaf/util/JavaVersion.java, recaf-core/src/main/java/me/coley/recaf/util/OperatingSystem.java, recaf-core/src/main/java/me/coley/recaf/util/logging/InterceptingLogger.java, recaf-core/src/main/java/me/coley/recaf/util/logging/Logging.java, recaf-core/src/test/java/me/coley/recaf/compile/JavacTests.java, recaf-core/src/test/resources/content-sources/SampleFailing.java
Implements the Compiler abstract class with `javac` integration.
This requires some creation of a few utilities:
- Common Recaf directories
- Knowing the current OS for specific cases
- Getting the current Java version
- Logging
=> 3X: Add javac compiler implementation

recaf-ui/src/main/java/me/coley/recaf/config/ConfigContainer.java, recaf-ui/src/main/java/me/coley/recaf/config/ConfigID.java, recaf-ui/src/main/java/me/coley/recaf/config/ConfigRegistry.java, recaf-ui/src/main/java/me/coley/recaf/config/Configs.java, recaf-ui/src/main/java/me/coley/recaf/config/Group.java, recaf-ui/src/main/java/me/coley/recaf/config/container/DisplayConfig.java, recaf-ui/src/main/java/me/coley/recaf/presentation/GuiPresentation.java, recaf-ui/src/main/java/me/coley/recaf/ui/control/tree/item/ResourceItem.java, recaf-ui/src/main/java/me/coley/recaf/util/ReflectionUtil.java, recaf-ui/src/main/resources/lang/en.lang
This is the setup for the config system in Recaf 3X.
Major differences:
- Not bound to controller for easy access from anywhere
- Easily extensible by registering new config containers
The config is no longer bound to the controller because the controller logic is for the most part, only what is defined in the `core` module. The `core` functionality will be handled as a library and config items will be passed to it over method parameters. This fixes a long standing issue of config and controller access being intertwined with core logic.
As for extensibility, the way the system works in 2X makes it a bit wonky for adding custom additions. This should make it very easy to create plugins with multiple configurable values.
=> 3X: Config system

pom.xml, src/main/java/me/coley/recaf/Recaf.java, src/main/java/me/coley/recaf/workspace/JarResource.java
* Fix https://github.com/Col-E/Recaf/issues/440 / https://github.com/Col-E/Recaf/issues/403
=> Backport alternative class reading method for invalid class CRCs

pom.xml, src/main/java/me/coley/recaf/Recaf.java, src/main/java/me/coley/recaf/workspace/JarResource.java
* Fix potential file handle leak from zip CRC logic backport
=> Fix potential file handle leak from zip CRC logic backport

build.gradle, recaf-ui/src/main/java/me/coley/recaf/ui/pane/elf/ElfExplorerPane.java, recaf-ui/src/main/java/me/coley/recaf/ui/pane/elf/ElfHeaderDisplayMode.java, recaf-ui/src/main/java/me/coley/recaf/ui/pane/elf/ProgramHeaderDisplayMode.java, recaf-ui/src/main/java/me/coley/recaf/ui/pane/elf/SectionHeaderDisplayMode.java, recaf-ui/src/main/java/me/coley/recaf/ui/pane/table/SizedDataTypeTable.java
* jelf is now updated to 0.7.0, field names are accurate to ELF specification now
* Fixed bug where selecting a section header would show information about the section header below it, not the actual current one
* Added support for PT_GNU_EH_FRAME, PT_GNU_STACK and PT_GNU_RELRO program header types
=> Update jelf to 0.7.0 + small ELF explorer improvements

recaf-core/src/main/java/me/coley/recaf/util/Exporter.java, recaf-core/src/main/java/me/coley/recaf/util/visitor/ValidationClassReader.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/ClassPatchingListener.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/MultiDexClassMap.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/Resource.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/ApkContentSource.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/ArchiveFileContentSource.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/ClassContentSource.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/ContainerContentSource.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/ContentCollection.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/ContentSource.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/ContentSourceListener.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/DirectoryContentSource.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/EmptyContentSource.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/FileContentSource.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/MavenContentSource.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/UrlContentSource.java, recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/WarContentSource.java
`ContentSource#onRead` no longer directly dumps classes/files into `Resource` instances. Instead it puts them into a `ContentCollection` instance. This class has fields for:
* normal classes/files
* various obfuscated/illegal input 
The `ContentSourceListener` has been repurposed to only have a `pre` and `post` operation, where `post` can be used to handle the illegal input. 
---------
At the moment not all forms of illegal input are handled in the UI. The end goal would be to prompt users what they would like to do with different kinds of input if there are conflicts. For most inputs this shouldn't affect end-users dropping in normal jar files and stuff.
=> ContentSource refactoring

src/main/java/me/coley/recaf/ui/controls/view/FileViewport.java
It's reasonable to show text in UTF-8 instead of system default charset as most java developers use UTF-8.
This PR fixes encoding issue in text mode.
[sample.zip](https://github.com/Col-E/Recaf/files/8519355/sample.zip)
=> Use utf-8 instead of default charset in FileViewport text mode

recaf-ui/src/main/java/me/coley/recaf/ui/pane/ConfigPane.java, recaf-ui/src/main/java/me/coley/recaf/ui/util/Lang.java
- Added optional tooltips to config values using the translation key `[conf.[id].description]`
=> Added optional description tooltips to config values

recaf-ui/src/main/java/me/coley/recaf/ui/control/EnumComboBox.java, recaf-ui/src/main/java/me/coley/recaf/ui/control/config/ConfigEnum.java
This fixes combo boxes not updating when changing the language in the settings. The previous change introduced in c30b21c177a01dca2fcc78e85d127b5fd1adb070 seems to be ineffective. The fix is still a bit of a hack, but I couldn't find a better way to force the combo box to refresh without messing with the associated skin.
Before:
After
:
=> Fix ComboBox translation not updating when changing language

src/main/java/me/coley/recaf/parse/bytecode/Disassembler.java, src/main/java/me/coley/recaf/parse/bytecode/ast/ItfAST.java, src/main/java/me/coley/recaf/parse/bytecode/ast/MethodInsnAST.java, src/main/java/me/coley/recaf/parse/bytecode/parser/MethodInsnParser.java, src/test/java/me/coley/recaf/AssemblyAstTest.java, src/test/java/me/coley/recaf/AssemblyCasesTest.java
* Introduced an "itf" suffix to invokestatic calls to preserve the fact that it is calling an interface method, which is required by the JVM verifier.
* #454
=> Introduce "itf" suffix to invokestatic calls

recaf-ui/src/main/java/me/coley/recaf/ui/control/ManifestArea.java, recaf-ui/src/main/java/me/coley/recaf/ui/control/code/SyntaxArea.java, recaf-ui/src/main/java/me/coley/recaf/ui/control/code/java/JavaArea.java
https://github.com/Col-E/recaf-3x-issues/issues/102
It's this feature, but it adds only a `\t` before each line.
=> Add tab press for indent code in SyntaxArea

recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/BaseArg.java, recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/HandleInfo.java, recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/VariableReference.java, recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/arch/FieldDefinition.java, recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/arch/TryCatch.java, recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/insn/FieldInstruction.java, recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/insn/IndyInstruction.java, recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/insn/MethodInstruction.java, recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/insn/MultiArrayInstruction.java, recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/insn/TypeInstruction.java, recaf-core/src/main/java/me/coley/recaf/decompile/fallback/print/BasicClassPrintStrategy.java, recaf-core/src/main/java/me/coley/recaf/decompile/fallback/print/BasicFieldPrintStrategy.java, recaf-core/src/main/java/me/coley/recaf/decompile/fallback/print/BasicMethodPrintStrategy.java, recaf-core/src/main/java/me/coley/recaf/decompile/fallback/print/PrintBase.java, recaf-utils/src/main/java/me/coley/recaf/util/EscapeUtil.java
- `EscapeUtil` method name is now `escapeNonValid` instead of `escapeSpace`
- Escaping of parser tropes like: `"` or `//`
- Added escaping to some instructions who didn't have it
=> Fix assembler escaping issues

recaf-ui/src/main/java/me/coley/recaf/ui/control/config/ConfigDecompiler.java
* Fix IllegalArgumentException by setting decompiler field to decompiler name.
=> Fix exception caused by mismatching types when setting default decompiler

settings.gradle
* N/A
* Automatic toolchain resolving
=> Fix toolchain resolving

build.gradle, recaf-assembler/build.gradle, recaf-assembler/src/main/java/me/coley/recaf/assemble/transformer/AstToMethodTransformer.java
=> Fix: unescape string using apache library

src/main/java/me/coley/recaf/parse/bytecode/parser/AliasDeclarationParser.java, src/main/java/me/coley/recaf/parse/bytecode/parser/HandleParser.java, src/main/java/me/coley/recaf/parse/bytecode/parser/IincInsnParser.java, src/main/java/me/coley/recaf/parse/bytecode/parser/IntInsnParser.java, src/main/java/me/coley/recaf/parse/bytecode/parser/InvokeDynamicParser.java, src/main/java/me/coley/recaf/parse/bytecode/parser/JumpInsnParser.java, src/main/java/me/coley/recaf/parse/bytecode/parser/LineInsnParser.java, src/main/java/me/coley/recaf/parse/bytecode/parser/LookupSwitchInsnParser.java, src/main/java/me/coley/recaf/parse/bytecode/parser/MethodInsnParser.java, src/main/java/me/coley/recaf/parse/bytecode/parser/MultiArrayParser.java, src/main/java/me/coley/recaf/parse/bytecode/parser/SignatureParser.java, src/main/java/me/coley/recaf/parse/bytecode/parser/TableSwitchInsnParser.java, src/main/java/me/coley/recaf/parse/bytecode/parser/TypeInsnParser.java, src/main/java/me/coley/recaf/parse/bytecode/parser/VarInsnParser.java
* Nada
* A bunch of instruction parsers had the word "parameters" misspelled as "paramters" in an error except for one, which was already fixed 3 years ago.
=> fix: Fixed misspelling of "parameters" in some instruction parsers

jitpack.yml
Nothing
Jitpack
By default, jitpack uses java 8, this PR adds a `jitpack.yml` that tells it to use java 17
=> Fix jitpack

recaf-core/src/main/java/software/coley/recaf/services/search/query/AbstractValueQuery.java, recaf-core/src/main/java/software/coley/recaf/util/BlwUtil.java
Allow the search to match switch labels, and allow the result to be displayed in the result panel as 'lookupswitch'.
In my usecase, I have a huge codebase with a lot of 'switch' but I can't search for their  labels in Recaf 4.X (they are number):
Results:
Without the edit in BlwUtil, the instruction is passed to ``execute(Instruction instruction)` and thus nothing is displayed.
=> feat: detect lookup switch labels in search results

recaf-ui/src/main/java/software/coley/recaf/ui/control/VirtualizedScrollPaneWrapper.java, recaf-ui/src/main/java/software/coley/recaf/ui/control/richtext/Editor.java, recaf-ui/src/main/java/software/coley/recaf/util/NodeEvents.java
Closes https://github.com/Col-E/Recaf/issues/858
None
=> Auto-scroll with middle mouse button

recaf-ui/src/main/java/software/coley/recaf/ui/pane/MappingGeneratorPane.java
Nothing
This error:
```
java.lang.IllegalArgumentException: Children: duplicate children added: parent = Grid hgap=5.0, vgap=5.0, alignment=TOP_LEFT
at javafx.graphics@22.0.1/javafx.scene.Parent$3.onProposedChange(Parent.java:562)
at javafx.base@22.0.1/com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:238)
at javafx.base@22.0.1/com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:105)
at javafx.graphics@22.0.1/javafx.scene.layout.GridPane.addRow(GridPane.java:1032)
at software.coley.recaf.ui.pane.MappingGeneratorPane$IncludeName.fillConfigurator(MappingGeneratorPane.java:791)
at software.coley.recaf.ui.pane.MappingGeneratorPane$FilterWithConfigNode.getConfigurator(MappingGeneratorPane.java:1006)
at …
```
=> Fix error in mapping generator

recaf-core/src/main/java/software/coley/recaf/services/mapping/format/EnigmaMappings.java, recaf-core/src/test/java/software/coley/recaf/services/mapping/format/MappingImplementationTest.java
Rewrote the parser.
- Still using indices for fast string parsing
- Fixed inner classes again
- Should be able to create better error messages
- Improved tolerance for bogus spaces
- Basic indent validation
- No state machine, state is handled by code flow
Please give feedback on complexity and maintainability.
~~It seems to a little faster than the previous one.~~ Speed about the same as the previous new impl.
Due to lambda usage `MemberMappingsConsumer` for code clarity, first shot speed is a little slower.
=> Enigma mappings improve 2
